steps:
  # Step 1: Run Jest tests
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - 'run'
      - 'test'
    # Exit the build if tests fail
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - '.'
  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
  # Step 3: Tag the image for Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - 'valentingarciairiart/celfahr:js2'
  # Step 4: Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'login'
      - '-u'
      - '${_DOCKER_USERNAME}'
      - '-p'
      - '${_DOCKER_PASSWORD}'
  # Step 5: Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/celfahr:js2'
  # Step 6: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'celsiusfahr-service'
      - '--image'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated' 

# List of images for Cloud Build to recognize
images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
  - 'valentingarciairiart/celfahr:js2'
