steps:
  # Step 12: Autenticar con Azure y configurar kubectl para AKS
  - name: 'mcr.microsoft.com/azure-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        az login --service-principal -u "$$AZURE_CLIENT_ID" -p "$$AZURE_CLIENT_SECRET" --tenant "$$AZURE_TENANT_ID"
        az aks get-credentials --resource-group "$$AKS_RESOURCE_GROUP" --name $_AKS_CLUSTER_NAME
    secretEnv: ['AZURE_CLIENT_ID', 'AZURE_CLIENT_SECRET', 'AZURE_TENANT_ID', 'AKS_RESOURCE_GROUP']

  # Step 13: Verificar si el namespace existe y crearlo si no
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if kubectl get namespace $_NAMESPACE &> /dev/null; then
          echo "Namespace $_NAMESPACE exists, skipping creation..."
        else
          kubectl create namespace $_NAMESPACE
        fi
    secretEnv: ['AZURE_CLIENT_ID', 'AZURE_CLIENT_SECRET', 'AZURE_TENANT_ID', 'AKS_RESOURCE_GROUP']
    
  # Step 14: Instalar Helm Chart desde GitHub Pages si no hay un release
  - name: 'alpine/helm'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if ! helm repo list | grep '$_REPO_HELM_GIT'; then
          helm repo add $_REPO_NAME $_REPO_HELM_GIT
        fi
        helm repo update
        if ! helm ls -n $_NAMESPACE | grep '$_HELM_NAME'; then
          helm install $_RELEASE $_REPO_NAME/$_CHART_NAME --namespace $_NAMESPACE
        else
          echo "Skipping Helm install since a release already exists."
        fi
    secretEnv: ['AZURE_CLIENT_ID', 'AZURE_CLIENT_SECRET', 'AZURE_TENANT_ID', 'AKS_RESOURCE_GROUP']

availableSecrets:
  secretManager:
    - versionName: "projects/still-descent-423419-c7/secrets/azclid/versions/latest"
      env: "AZURE_CLIENT_ID"
    - versionName: "projects/still-descent-423419-c7/secrets/azclisec/versions/latest"
      env: "AZURE_CLIENT_SECRET"
    - versionName: "projects/still-descent-423419-c7/secrets/aztenant/versions/latest"
      env: "AZURE_TENANT_ID"
    - versionName: "projects/still-descent-423419-c7/secrets/azrg/versions/latest"
      env: "AKS_RESOURCE_GROUP"

