steps:
  # Step 1: Run Jest tests
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - 'run'
      - 'test' 

  # Step 2: Construir la imagen Docker si los tests pasan
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js'
      - '.'

  # Step 3: Push la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js'
  # Step 4: Tag la imagen para Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js'
      - 'valentingarciairiart/celfahr:js'

  # Step 5: Login en Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'login'
      - '-u'
      - '${_DOCKER_USERNAME}'
      - '-p'
      - '${_DOCKER_PASSWORD}'

  # Step 6: Push la imagen a Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/celfahr:js'

  # Step 7: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'celsiusfahr-service'
      - '--image'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated' 

# Lista de imágenes para que Cloud Build las reconozca
images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js'
  - 'valentingarciairiart/celfahr:js'
