steps:
  # Step 1: Install dependencies
  - name: 'node'
    entrypoint: 'npm'
    args: 
      - 'install'
  # Step 2: Run tests
  - name: 'node'
    entrypoint: 'npm'
    args: 
      - 'test'
  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - '.'
  # Step 4: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
  # Step 5: Tag the image for Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - 'valentingarciairiart/celfahr:js2'
  # Step 6: Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USER" --password-stdin
    secretEnv: ['DOCKER_USER', 'DOCKER_PASSWORD']
  # Step 7: Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/celfahr:js2'
  # Step 8: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'celsiusfahr-service'
      - '--image'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated' 
  # Step 9: Conditional deployment or apply
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if kubectl get service celsiusfahr-service -n valenfahr 2>/dev/null && kubectl get deployment celsiusfahr-deployment -n valenfahr 2>/dev/null; then
          kubectl set image deployment/celsiusfahr-deployment celsiusfahr-container=us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2 -n valenfahr
        else
          kubectl apply -f deployment.yaml -n valenfahr
        fi
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

# List of images for Cloud Build to recognize
images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
  - 'valentingarciairiart/celfahr:js2'

availableSecrets:
  secretManager:
  - versionName: "projects/still-descent-423419-c7/secrets/dckusr/versions/latest"
    env: "DOCKER_USER"
  - versionName: "projects/still-descent-423419-c7/secrets/dckpsw/versions/latest"
    env: "DOCKER_PASSWORD"
