steps:
  # Step 1: Install dependencies
  - name: 'node'
    entrypoint: 'npm'
    args: 
      - 'install'
  
  # Step 2: Run tests
  - name: 'node'
    entrypoint: 'npm'
    args: 
      - 'test'
  
  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - '.'
  
  # Step 4: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
  
  # Step 5: Tag the image for Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
      - 'valentingarciairiart/celfahr:js2'
  
  # Step 6: Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USER" --password-stdin
    secretEnv: ['DOCKER_USER', 'DOCKER_PASSWORD']
  
  # Step 7: Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'valentingarciairiart/celfahr:js2'
  
  # Step 8: Autenticar con Azure y configurar kubectl
  - name: 'mcr.microsoft.com/azure-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        az login --service-principal -u "$$AZURE_CLIENT_ID" -p "$$AZURE_CLIENT_SECRET" --tenant "$$AZURE_TENANT_ID"
        az aks get-credentials --resource-group "$$AKS_RESOURCE_GROUP" --name $_AKS_CLUSTER_NAME
    secretEnv: ['AZURE_CLIENT_ID', 'AZURE_CLIENT_SECRET', 'AZURE_TENANT_ID','AKS_RESOURCE_GROUP']

images:
  - 'us-docker.pkg.dev/still-descent-423419-c7/celfahr/celfahr:js2'
  - 'valentingarciairiart/celfahr:js2'

availableSecrets:
  secretManager:
  - versionName: "projects/still-descent-423419-c7/secrets/dckusr/versions/latest"
    env: "DOCKER_USER"
  - versionName: "projects/still-descent-423419-c7/secrets/dckpsw/versions/latest"
    env: "DOCKER_PASSWORD"
  - versionName: "projects/still-descent-423419-c7/secrets/azclid/versions/latest"
    env: "AZURE_CLIENT_ID"
  - versionName: "projects/still-descent-423419-c7/secrets/azclisec/versions/latest"
    env: "AZURE_CLIENT_SECRET"
  - versionName: "projects/still-descent-423419-c7/secrets/aztenant/versions/latest"
    env: "AZURE_TENANT_ID"
  - versionName: "projects/still-descent-423419-c7/secrets/azrg/versions/latest"
    env: "AKS_RESOURCE_GROUP"

    
