apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-celfahr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-celfahr
  template:
    metadata:
      labels:
        app: app-celfahr
      annotations:
        redeployTimestamp: "initial-deploy" # Esto se actualizará con el comando kubectl patch
    spec:
      containers:
        - name: celfahr-container
          image: valentingarciairiart/celfahr:js9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: celfahr-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: app-celfahr
