replicaCount: 1

image:
  repository: valentingarciairiart/celfahr
  tag: v3
  pullPolicy: Always

resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 512Mi


ingress:
  host: valentincelsius.modelodevops.sociuschile.cl
  secretName: valentincelsius-secret-socius
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  paths:
    - path: /?(.*)
      pathType: Prefix
      backend:
        service:
          name: {{ include "your-chart.serviceName" . }}
          port:
            number: 80
  className: nginx  # Variable para la clase del Ingress

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

namespace: valenfahr

containerPort: 3000
