apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: celfahr-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging # esto es para usar la CA de azure configurado 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - valentincelsius.modelodevops.sociuschile.cl
    secretName: valentincelsius-secret-socius
  rules:
    - host: valentincelsius.modelodevops.sociuschile.cl
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: celfahr-service
                port:
                  number: 80