apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}
  labels:
    app: {{ include "my-helm-chart.name" . }}
    chart: "{{ include "my-helm-chart.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "my-helm-chart.name" . }}
